sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  upload:
    #    文件上传配置
    uploadDir: E:\daima\java\CangQiongWaiMai\nginx-1.20.2\media\
    #    默认后缀
    imageSuffix: .jpg
    #    图片地址
    imgUrl: http://localhost/media/
    #    上传文件名中是否使用原文件名
    useOriginalName: false

  wechat:
    appid: wx325ca24552ebf1c7
    secret: 7fdbb89a860df49dc92874200c925417
#    mchid:
#    mchSerialNo:
#    privateKeyFilePath:
#    apiV3Key:
#    weChatPayCertFilePath:
#    notifyUrl:
#    refundNotifyUrl:

spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1